#+TITLE:  Org exporter for curriculum vitaes
#+AUTHOR: Óscar Nájera
#+EMAIL:  hello@oscarnajera.com
#+DATE:   2018 Mar 22
#+LATEX_HEADER: \usepackage[top=2cm,bottom=2.5cm,left=3cm,right=3cm]{geometry}
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+STARTUP: hideblocks
#+OPTIONS: toc:nil num:nil
# This is for syntax highlight
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{friendly}
#+LaTeX_HEADER: \newminted{common-lisp}{fontsize=\footnotesize}

This project aim on generating from an orgmode file with reasonably ordered
items of live to export to a latex file which compiles into a reasonably
nice CV.

* DONE Base environment
- State "DONE"       from "TODO"       [2018-03-22 Thu 17:57]
I have the basic cv template that gets exported
* TODO org-exporter for latex
:LOGBOOK:
CLOCK: [2018-03-22 Thu 23:17]--[2018-03-23 Fri 03:25] =>  4:08
CLOCK: [2018-03-22 Thu 17:58]--[2018-03-22 Thu 18:37] =>  0:39
:END:
I'm comparing the contents of the template export function. It looks that
this one give the genera document layout and this is where I shall insert
them data.
comparing ox-latex, ox-beamer, ox-koma

I learned quite a lot from the main latex and koma files. Currently I
already reproduce latex export, which is not much as that was already a
working output. But now I have the specific keywords for the personal
information part.
** TODO Process headings with properties into cventries
** TODO Incorporate from beamer how the do the theme settings
This looks like a fancy way to avoid repetition. Have a look too trying to
imitate that behavior for the other personal tags of social media,url,phones.
* TODO Tune in latex export
