#+TITLE:  Org exporter for curriculum vitae
#+AUTHOR: Óscar Nájera
#+EMAIL:  hello@oscarnajera.com
#+DATE:   2018 Mar 22
#+LATEX_HEADER: \usepackage[top=2cm,bottom=2.5cm,left=3cm,right=3cm]{geometry}
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_CLASS_OPTIONS: [a4paper,12pt]
#+STARTUP: hideblocks
#+OPTIONS: toc:nil num:nil
# This is for syntax highlight
#+LaTeX_HEADER: \usepackage{minted}
#+LaTeX_HEADER: \usemintedstyle{friendly}
#+LaTeX_HEADER: \newminted{common-lisp}{fontsize=\footnotesize}

This project aims on generating from an orgmode file with reasonably ordered
items of live to export to a latex file which compiles into a reasonably
nice CV.

* Update readme
** TODO examples [0/2]
*** TODO pictures
*** TODO scripts
* TODO Make a package
Complete the file with license and how to load it.
* DONE Base environment
- State "DONE"       from "TODO"       [2018-03-22 Thu 17:57]
I have the basic cv template that gets exported
* DONE org-exporter for latex
- State "DONE"       from "TODO"       [2018-04-05 Thu 03:04]
:LOGBOOK:
CLOCK: [2018-03-22 Thu 23:17]--[2018-03-23 Fri 03:25] =>  4:08
CLOCK: [2018-03-22 Thu 17:58]--[2018-03-22 Thu 18:37] =>  0:39
:END:
I'm comparing the contents of the template export function. It looks that
this one give the genera document layout and this is where I shall insert
them data.
comparing ox-latex, ox-beamer, ox-koma

I learned quite a lot from the main latex and koma files. Currently I
already reproduce latex export, which is not much as that was already a
working output. But now I have the specific keywords for the personal
information part.
** DONE Process headings with properties into cventries
- State "DONE"       from "TODO"       [2018-03-24 Sat 03:02]
:LOGBOOK:
CLOCK: [2018-03-23 Fri 22:54]--[2018-03-24 Sat 03:05] =>  4:11
CLOCK: [2018-03-23 Fri 14:41]--[2018-03-23 Fri 19:05] =>  4:24
:END:
I'm constructing the entries quite fine but somehow the intermedia function
refuses to get written even when it appears that its output is correct.

I don't fully understand. But it appear that I need to call the exporter
again within the exporting of the headings. This maybe is what helps
getting down the subtrees and getting to the latex output.
** DONE Incorporate from beamer how the do the theme settings
- State "DONE"       from "TODO"       [2018-03-23 Fri 16:01]
This looks like a fancy way to avoid repetition. Have a look too trying to
imitate that behavior for the other personal tags of social media,url,phones.
* DONE Markdown exporter for integration with hugo blog
